@echo off
setlocal EnableDelayedExpansion
rem ===========================================================================
rem  install-autostart.bat - early, non-admin autostart for the AnniAudio mixer
rem  via a Task Scheduler logon task.
rem
rem  Why a scheduled task instead of the Run key: a logon-triggered task is
rem  handled by the Task Scheduler service OUTSIDE the Run-key/Startup-folder
rem  startup throttle (the deliberate "let the desktop settle" delay Windows
rem  applies to Run entries), so the mixer comes up around the same time as your
rem  other tray apps instead of well after them. It still runs in your USER
rem  session (LogonType Interactive), which is required - WASAPI audio endpoints
rem  only exist in the user session, so the mixer can never be a plain boot-time
rem  service.
rem
rem  It also adds a Run-key entry purely so the item shows up in Task Manager's
rem  Startup tab (scheduled tasks never appear there). Both point at the same
rem  single-instance-guarded launcher, so they cannot double-start the mixer.
rem
rem  No admin required: the task runs at Limited (un-elevated) run level as the
rem  current interactive user.
rem
rem  Usage:
rem    install-autostart.bat            install (task + Task Manager entry)
rem    install-autostart.bat uninstall  remove everything this script made
rem ===========================================================================

cd /d "%~dp0"
set "ROOT=%CD%"
set "TASK=AnniAudioMixer"
set "RUNVAL=AnniAudioMixer"
set "APP_DIR=%APPDATA%\AnniAudio"
set "VBS=%APP_DIR%\AnniAudioMixer.vbs"

if /I "%~1"=="uninstall" goto :uninstall
if /I "%~1"=="/uninstall" goto :uninstall
if /I "%~1"=="remove" goto :uninstall

rem ---------------------------------------------------------------------------
rem Install
rem ---------------------------------------------------------------------------
if not exist "%ROOT%\build\bin\Release\route_cli.exe" (
    echo ERROR: route_cli.exe not found. Build it first with:
    echo   cmake --build build --target route_cli --config Release
    pause
    exit /b 1
)

set "CONFIG=%ROOT%\config\mixers\main.json"
if not exist "%CONFIG%" set "CONFIG=%ROOT%\config\mixers\default.json"

if not exist "%APP_DIR%" mkdir "%APP_DIR%"

rem Remove the old Startup-folder launcher from a legacy installer, if present,
rem so nothing starts the mixer twice.
set "LEGACY_VBS=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\AnniAudioMixer.vbs"
if exist "%LEGACY_VBS%" del "%LEGACY_VBS%"

rem --- Write the single-instance-guarded hidden launcher ---------------------
rem The guard (skip if route_cli.exe is already running) is what lets the task
rem and the Run-key entry coexist without ever starting two mixers.
>  "%VBS%" echo ' Auto-generated by install-autostart.bat - starts the AnniAudio mixer hidden at logon.
>> "%VBS%" echo Option Explicit
>> "%VBS%" echo Dim sh, wmi, procs
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo On Error Resume Next
>> "%VBS%" echo Set wmi = GetObject("winmgmts:\\.\root\cimv2")
>> "%VBS%" echo If Not wmi Is Nothing Then
>> "%VBS%" echo   Set procs = wmi.ExecQuery("SELECT ProcessId FROM Win32_Process WHERE Name='route_cli.exe'")
>> "%VBS%" echo   If Not procs Is Nothing Then If procs.Count ^> 0 Then WScript.Quit 0
>> "%VBS%" echo End If
>> "%VBS%" echo On Error Goto 0
>> "%VBS%" echo sh.CurrentDirectory = "%ROOT%"
>> "%VBS%" echo sh.Run """%ROOT%\build\bin\Release\route_cli.exe"" mixer ""%CONFIG%"" --port 8850", 0, False

if not exist "%VBS%" (
    echo ERROR: failed to write launcher %VBS%
    pause
    exit /b 1
)

rem --- Register the logon-triggered task (via PowerShell ScheduledTasks) ------
rem Limited run level = no admin. Interactive logon type = user session (WASAPI).
rem ExecutionTimeLimit 0 = never auto-killed (the mixer runs indefinitely; the
rem default task limit is 3 days, which would kill a long session).
rem Priority 5 = normal process priority (the audio thread is already MMCSS
rem real-time, so a higher class buys nothing here).
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "try {" ^
  "  $who = \"$env:USERDOMAIN\$env:USERNAME\";" ^
  "  $a = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ([char]34 + '%VBS%' + [char]34);" ^
  "  $t = New-ScheduledTaskTrigger -AtLogOn -User $who;" ^
  "  $p = New-ScheduledTaskPrincipal -UserId $who -LogonType Interactive -RunLevel Limited;" ^
  "  $s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit ([TimeSpan]::Zero) -Priority 5 -MultipleInstances IgnoreNew;" ^
  "  Register-ScheduledTask -TaskName '%TASK%' -Description 'Starts the AnniAudio mixer hidden at logon, before the Run-key startup throttle.' -Action $a -Trigger $t -Principal $p -Settings $s -Force | Out-Null;" ^
  "  exit 0" ^
  "} catch { Write-Host $_.Exception.Message; exit 1 }"

if errorlevel 1 (
    echo.
    echo WARNING: could not register the scheduled task.
    echo If this was an access error, run this .bat once "as administrator" and
    echo it will register cleanly. The Task Manager entry below is still added.
) else (
    echo Registered task: \%TASK%  ^(At log on, un-elevated, no time limit^)
)

rem --- Run-key entry: only so the item is visible in Task Manager Startup -----
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "%RUNVAL%" /t REG_SZ /d "wscript.exe \"%VBS%\"" /f >nul
echo Added Task Manager Startup entry: %RUNVAL%

rem --- Start now if it isn't already running (the guard makes this safe) ------
wscript "%VBS%"

echo.
echo Done. The mixer now starts hidden at logon via the scheduled task
echo ^(config: %CONFIG%^).
echo.
echo Notes:
echo  - The scheduled TASK is the real autostart. The Task Manager Startup entry
echo    is for visibility; toggling it OFF there does NOT stop autostart.
echo  - To fully disable / remove everything: install-autostart.bat uninstall
echo  - Manage the task directly in Task Scheduler ^(taskschd.msc -^> %TASK%^).
goto :eof

rem ---------------------------------------------------------------------------
rem Uninstall
rem ---------------------------------------------------------------------------
:uninstall
echo Removing AnniAudio autostart...
schtasks /delete /tn "%TASK%" /f >nul 2>&1 && echo  - removed scheduled task %TASK% || echo  - no scheduled task %TASK% found
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "%RUNVAL%" /f >nul 2>&1 && echo  - removed Task Manager Startup entry || echo  - no Startup entry found
if exist "%VBS%" ( del "%VBS%" && echo  - removed launcher %VBS% )
echo Done. ^(This does not stop a mixer that is already running - use stop-mixer.bat for that.^)
goto :eof
