@echo off
setlocal
rem Installs a hidden-at-logon launcher for the AnniAudio mixer.
rem
rem No admin rights needed: this writes a .vbs into the current user's AppData
rem and adds it to the HKCU Run registry key. The mixer MUST run in the user
rem session (not as a service) because WASAPI audio endpoints only exist there.
rem The Run key is processed earlier than the Startup folder, so the mixer starts
rem sooner after logon. Remove again with uninstall-autostart.bat.

cd /d "%~dp0"
set ROOT=%CD%

if not exist "%ROOT%\build\bin\Release\route_cli.exe" (
    echo ERROR: route_cli.exe not found. Build it first with:
    echo   cmake --build build --target route_cli --config Release
    pause
    exit /b 1
)

set CONFIG=%ROOT%\config\mixers\main.json
if not exist "%CONFIG%" set CONFIG=%ROOT%\config\mixers\default.json

set APP_DIR=%APPDATA%\AnniAudio
set VBS=%APP_DIR%\AnniAudioMixer.vbs
set LEGACY_VBS=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\AnniAudioMixer.vbs

if not exist "%APP_DIR%" mkdir "%APP_DIR%"

rem Remove the old Startup-folder launcher so it does not run twice.
if exist "%LEGACY_VBS%" del "%LEGACY_VBS%"

>  "%VBS%" echo ' Auto-generated by install-autostart.bat - starts the AnniAudio mixer hidden at logon.
>> "%VBS%" echo Dim sh
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo sh.CurrentDirectory = "%ROOT%"
>> "%VBS%" echo sh.Run """%ROOT%\build\bin\Release\route_cli.exe"" mixer ""%CONFIG%"" --port 8850", 0, False

reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v AnniAudioMixer /t REG_SZ /d "wscript.exe ""%VBS%""" /f >nul

echo Installed: %VBS%
echo Run key added: HKCU\...\Run\AnniAudioMixer
echo The mixer will now start hidden at every logon (config: %CONFIG%).
echo.
choice /C YN /M "Start it now (hidden)"
if errorlevel 2 goto :eof
wscript "%VBS%"
echo Started. Check http://127.0.0.1:8850/api/state or run mixer-tui.bat.
