@echo off
setlocal
rem Installs a hidden-at-logon launcher for the AnniAudio mixer.
rem
rem No admin rights needed: this drops a .vbs into the current user's Startup
rem folder that starts route_cli.exe with a hidden window. The mixer MUST run
rem in the user session (not as a service) because WASAPI audio endpoints only
rem exist there. Remove again with uninstall-autostart.bat.

cd /d "%~dp0"
set ROOT=%CD%

if not exist "%ROOT%\build\bin\Release\route_cli.exe" (
    echo ERROR: route_cli.exe not found. Build it first with:
    echo   cmake --build build --target route_cli --config Release
    pause
    exit /b 1
)

set CONFIG=%ROOT%\config\mixers\main.json
if not exist "%CONFIG%" set CONFIG=%ROOT%\config\mixers\default.json

set VBS=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\AnniAudioMixer.vbs

>  "%VBS%" echo ' Auto-generated by install-autostart.bat - starts the AnniAudio mixer hidden at logon.
>> "%VBS%" echo Dim sh
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo sh.CurrentDirectory = "%ROOT%"
>> "%VBS%" echo sh.Run """%ROOT%\build\bin\Release\route_cli.exe"" mixer ""%CONFIG%"" --port 8850", 0, False

echo Installed: %VBS%
echo The mixer will now start hidden at every logon (config: %CONFIG%).
echo.
choice /C YN /M "Start it now (hidden)"
if errorlevel 2 goto :eof
wscript "%VBS%"
echo Started. Check http://127.0.0.1:8850/api/state or run mixer-tui.bat.
